### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by ZW-PRO** [AlexZou14/SCET#1]

**Comment by ZW-PRO** [comment]
你好 训练时候随即裁剪的GT patch size是多大，我看论文是416x416，如果我训练二倍gt是不是就是208x208

**Comment by AlexZou14** [comment]
GT patch size都是416x416，2倍放大下的输入图像大小是208x208

**Comment by ZW-PRO** [comment]
为什么会选取416而不是常见的256呢



---Original---
From: ***@***.***&gt;
Date: Sat, Apr 23, 2022 09:42 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [AlexZou14/SCET] HI (Issue #1)




 
GT patch size2倍是416x416，输入图像大小是208x208

**Comment by AlexZou14** [comment]
我们做了相应的消融实验，证明了大尺寸的图块训练效果会更好，为了在训练时间和性能上做到折中才选择了416

**Comment by laulampaul** [comment]
您好，想问问大概什么时候能够release代码？
